name: Get Support
description: Report an issue, ask a question, or request a feature
title: "[ISSUE] "
labels: []
assignees: []

body:

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Detailed description of the issue
    validations:
      required: true

  - type: dropdown
    id: network_name
    attributes:
      label: Network Name
      options:
        - Indonesia Open Network (ION)
        - NBSL
    validations:
      required: true

  - type: dropdown
    id: product_name
    attributes:
      label: Product
      options:
        - ONIX
        - DeDi
        - CATALG
        - DISCOVR
        
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - 🔴 Critical
        - 🟠 High
        - 🟡 Medium
        - 🟢 Low
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - Bug
        - Feature Request
        - Question
        - Documentation
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: "Status (set by assignee only)"
      description: "⚠️ Please leave this as 'Open' when submitting. Only the assignee should update this."
      options:
        - Open
        - In Progress
        - Blocked
        - Resolved
    validations:
      required: true
